export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: "from-docker-to-kubernetes",
      description:
        "A hands-on learning open source learning platform to help you master containerization and orchestration with Docker to Kubernetes.",
      ogImage: "/hero.png",
      ogImageComponent: "ShadcnDocs",
      ogImageColor: "light",
      umami: {
        enable: false,
        src: "https://cloud.umami.is/script.js",
        dataWebsiteId: "d793fbf3-461e-4e26-9ec9-4e9141df96ee",
      },
    },
    theme: {
      customizable: true,
      color: "zinc",
      radius: 1,
    },
    banner: {
      enable: true,
      showClose: true,
      content: "Welcome to **from-docker-to-kubernetes**",
      to: "https://github.com/NotHarshhaa/from-docker-to-kubernetes",
      target: "_blank",
      border: true,
    },
    header: {
      title: "from-docker-to-kubernetes",
      showTitle: true,
      logo: {
        light: "/logo.svg",
        dark: "/logo-dark.svg",
      },
      darkModeToggle: true,
      languageSwitcher: {
        enable: true,
        triggerType: "icon",
        dropdownType: "select",
      },
      nav: [
        {
          title: "Docs",
          links: [
            {
              title: "Getting Started",
              to: "/getting-started/introduction",
              description:
                "A hands-on learning open source learning platform to help you master containerization and orchestration with Docker to Kubernetes.",
              icon: "lucide:rocket",
            },
            {
              title: "Docker",
              to: "/learn-docker/docker/containers",
              description:
                "Explore all about Docker containers. From basic to advanced. From single container to multi-container applications.",
              icon: "lucide:container",
            },
            {
              title: "Kubernetes",
              to: "/learn-kubernetes/kubernetes/architecture",
              description:
                "Explore all about Kubernetes. From basic to advanced. From single node to multi-node applications.",
              icon: "lucide:ship-wheel",
            },
          ],
        },
        {
          title: "Credits",
          links: [
            {
              title: "shadcn-ui",
              to: "https://ui.shadcn.com/",
              description: "For the beautiful component design & docs design",
              target: "_blank",
            },
            {
              title: "shadcn-vue",
              to: "https://www.shadcn-vue.com/",
              description:
                "For the vue port of shadcn-ui & some docs component source",
              target: "_blank",
            },
            {
              title: "Docus",
              to: "https://docus.dev/",
              description: "For inspiration & some docs component source",
              target: "_blank",
            },
            {
              title: "Nuxt Content",
              to: "https://content.nuxt.com/",
              description: "Content made easy for Vue Developers",
              target: "_blank",
            },
          ],
        },
        {
          title: "Blog",
          to: "/blog",
          target: "_self",
          showLinkIcon: false,
        },
      ],
      links: [
        {
          icon: "lucide:coffee",
          to: "https://ko-fi.com/NotHarshhaa",
          target: "_blank",
        },
        {
          icon: "lucide:github",
          to: "https://github.com/NotHarshhaa/from-docker-to-kubernetes",
          target: "_blank",
        },
      ],
    },
    aside: {
      useLevel: true,
      collapse: true,
      collapseLevel: 1,
      folderStyle: "group",
      mobile: {
        enabled: true,
        placement: "left",
        initialState: "collapsed"
      }
    },
    main: {
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: true,
      codeCopyIcon: "lucide:clipboard",
      editLink: {
        enable: true,
        pattern:
          "https://github.com/NotHarshhaa/from-docker-to-kubernetes/edit/master/content/:path",
        text: "Edit this page",
        icon: "lucide:square-pen",
        placement: ["docsFooter"],
      },
      backToTop: true,
      codeIcon: {
        "package.json": "vscode-icons:file-type-node",
        "tsconfig.json": "vscode-icons:file-type-tsconfig",
        ".npmrc": "vscode-icons:file-type-npm",
        ".editorconfig": "vscode-icons:file-type-editorconfig",
        ".eslintrc": "vscode-icons:file-type-eslint",
        ".eslintrc.cjs": "vscode-icons:file-type-eslint",
        ".eslintignore": "vscode-icons:file-type-eslint",
        "eslint.config.js": "vscode-icons:file-type-eslint",
        "eslint.config.mjs": "vscode-icons:file-type-eslint",
        "eslint.config.cjs": "vscode-icons:file-type-eslint",
        ".gitignore": "vscode-icons:file-type-git",
        "yarn.lock": "vscode-icons:file-type-yarn",
        ".env": "vscode-icons:file-type-dotenv",
        ".env.example": "vscode-icons:file-type-dotenv",
        ".vscode/settings.json": "vscode-icons:file-type-vscode",
        nuxt: "vscode-icons:file-type-nuxt",
        ".nuxtrc": "vscode-icons:file-type-nuxt",
        ".nuxtignore": "vscode-icons:file-type-nuxt",
        "nuxt.config.js": "vscode-icons:file-type-nuxt",
        "nuxt.config.ts": "vscode-icons:file-type-nuxt",
        "nuxt.schema.ts": "vscode-icons:file-type-nuxt",
        "tailwind.config.js": "vscode-icons:file-type-tailwind",
        "tailwind.config.ts": "vscode-icons:file-type-tailwind",
        vue: "vscode-icons:file-type-vue",
        ts: "vscode-icons:file-type-typescript",
        tsx: "vscode-icons:file-type-typescript",
        mjs: "vscode-icons:file-type-js",
        cjs: "vscode-icons:file-type-js",
        js: "vscode-icons:file-type-js",
        jsx: "vscode-icons:file-type-js",
        md: "vscode-icons:file-type-markdown",
        mdc: "vscode-icons:file-type-markdown",
        css: "vscode-icons:file-type-css",
        py: "vscode-icons:file-type-python",
        npm: "vscode-icons:file-type-npm",
        pnpm: "vscode-icons:file-type-pnpm",
        npx: "vscode-icons:file-type-npm",
        yarn: "vscode-icons:file-type-yarn",
        bun: "vscode-icons:file-type-bun",
        yml: "vscode-icons:file-type-light-yaml",
        json: "vscode-icons:file-type-json",
        terminal: "lucide:terminal",
      },
    },
    footer: {
      credits: "Built with ❤️ by the ProDevOpsGuy Tech Community",
      links: [
        {
          icon: "lucide:github",
          title: "GitHub",
          to: "https://github.com/NotHarshhaa",
          target: "_blank",
          description: "View our source code",
        },
        {
          icon: "lucide:message-circle",
          title: "Telegram",
          to: "https://t.me/NotHarshhaa",
          target: "_blank",
          description: "Join our community",
        },
        {
          icon: "lucide:linkedin",
          title: "LinkedIn",
          to: "https://linkedin.com/in/harshhaa-vardhan-reddy",
          target: "_blank",
          description: "Connect with us",
        },
        {
          icon: "lucide:globe",
          title: "Website",
          to: "https://link.notharshhaa.site",
          target: "_blank",
          description: "Visit our website",
        },
        {
          icon: "lucide:book-open",
          title: "Documentation",
          to: "/getting-started/introduction",
          target: "_self",
          description: "Read our docs",
        },
      ],
      showCredits: true,
      showLinks: true,
      showLinkIcons: true,
      linkIconPlacement: "left",
      linkStyle: "button",
      mobileLayout: "stack",
      mobileBreakpoint: "sm",
    },
    toc: {
      enable: true,
      enableInMobile: false,
      enableInHomepage: false,
      title: "On this page",
      links: [
        {
          title: "Star on GitHub",
          icon: "lucide:star",
          to: "https://github.com/NotHarshhaa/from-docker-to-kubernetes",
          target: "_blank",
          showLinkIcon: true,
        },
        {
          title: "Create Issues",
          icon: "lucide:circle-dot",
          to: "https://github.com/NotHarshhaa/from-docker-to-kubernetes/issues",
          target: "_blank",
          showLinkIcon: true,
        },
      ],
      iconLinks: [
        {
          icon: "lucide:coffee",
          to: "https://ko-fi.com/NotHarshhaa",
          target: "_blank",
        },
        {
          icon: "lucide:twitter",
          to: "https://x.com/NotHarshhaa",
          target: "_blank",
        },
        {
          icon: "lucide-lab:butterfly",
          to: "https://bsky.app/profile/NotHarshhaa.bsky.social",
          target: "_blank",
        },
      ],
      carbonAds: {
        enable: false,
        disableInDev: true,
        disableInMobile: false,
        fallback: false,
        fallbackMessage: "Please support us by disabling your ad blocker.",
        code: "CW7ITKJN",
        placement: "shadcn-docs-nuxtvercelapp",
        format: "cover",
      },
    },
    search: {
      enable: true,
      inAside: false,
      style: "input",
    },
    data: {},
  },
});
